FROM golang:1.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o worker ./cmd/worker

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/worker .
CMD ["./worker"]
